import type { Metadata } from "next";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { SITE_URL } from "@/lib/seo/metadata";

export const revalidate = 3600;

export const metadata: Metadata = {
  title: "All 43.469 Giocondas",
  description:
    "The full dataset of Giocondas generated by 12 AI models trained on Argentine artists. Coming soon: a 3D Interstellar-style cloud map where each Gioconda is placed according to the LoRA weights of its style.",
  alternates: { canonical: `${SITE_URL}/giocondas` },
};

export default async function GiocondasIndex() {
  const supabase = await createClient();
  const { data: styles } = await supabase
    .from("styles")
    .select("name, artist_full_name, artist_slug")
    .order("name");

  const { count } = await supabase
    .from("giocondas")
    .select("*", { count: "exact", head: true });

  return (
    <main className="min-h-dvh bg-[#0a0d13] text-neutral-100">
      <div className="mx-auto max-w-4xl px-4 py-16 sm:px-8 sm:py-24">
        <Link href="/" className="text-sm text-neutral-400 hover:text-neutral-200">
          ← back to the Louvre
        </Link>
        <h1 className="mt-6 font-serif text-4xl leading-tight sm:text-5xl">
          All {count?.toLocaleString("en-US")} Giocondas
        </h1>
        <p className="mt-4 max-w-2xl text-neutral-400">
          A constellation of Mona Lisas reimagined by 12 open-source AI models
          independently trained by Nicolás Ruarte on works of Argentine masters
          and popular visual languages.
        </p>

        <section className="mt-12">
          <h2 className="font-serif text-lg text-neutral-200">Styles (LoRAs) in the dataset</h2>
          <ul className="mt-4 grid grid-cols-1 gap-2 text-sm sm:grid-cols-2">
            {(styles ?? []).map((s) => (
              <li key={s.name} className="rounded-md border border-neutral-800/60 bg-neutral-900/40 px-4 py-3">
                <div className="font-medium text-neutral-100">
                  {s.artist_full_name ?? s.name}
                </div>
                <div className="mt-0.5 font-mono text-xs text-neutral-500">{s.name}</div>
              </li>
            ))}
          </ul>
        </section>

        <section className="mt-12 rounded-xl border border-neutral-800/60 bg-neutral-900/30 p-6 text-sm leading-relaxed text-neutral-300">
          <h2 className="font-serif text-lg text-neutral-100">3D cloud map — coming soon</h2>
          <p className="mt-2">
            Each Gioconda will be placed in a 3D space using a gravitational layout
            derived from its LoRA weight vector. Pure styles cluster near their
            style anchor; mixed styles drift between them — a visual
            representation of the hybridization of cultural identities.
          </p>
          <p className="mt-2">
            The installation will also incorporate a live generator producing new
            Giocondas every few minutes.
          </p>
        </section>

        <section className="mt-12">
          <h2 className="font-serif text-lg text-neutral-200">Browse by ID</h2>
          <p className="mt-2 text-sm text-neutral-400">
            Any Gioconda can be visited directly at{" "}
            <code className="rounded bg-neutral-900 px-1.5 py-0.5 font-mono text-xs">
              /giocondas/&lt;id&gt;
            </code>{" "}
            from 1 to {count?.toLocaleString("en-US")}. Try{" "}
            {[1, 1000, 20000, count ?? 43469].map((n, i, arr) => (
              <span key={n}>
                <Link
                  href={`/giocondas/${n}`}
                  className="underline decoration-neutral-600 underline-offset-2 hover:text-neutral-100"
                >
                  #{n}
                </Link>
                {i < arr.length - 1 ? ", " : "."}
              </span>
            ))}
          </p>
        </section>
      </div>
    </main>
  );
}
